### ISSUE TITLE
Discard old logs

### ISSUE THREAD

**Issue by OpenByteDev** [tschroedter/idasen-desk#14]
The program should discard old log information. `C:\ProgramData\Idasen.SystemTray.log` is 1GB on my machine.

**Comment by tschroedter** [comment]
I will have a look when I have some time. The logging is based on Serilog and can be configured. I will most likely add support for a configuration file (appsettings.json). The default will restrict the file size and rolling log files with a limit.

**Comment by tschroedter** [comment]
I've create a new release which will use 5 rolling log files with a max. size of 10 MBytes. Optional you can use your own settings by providing a appsettings.json file in the .exe folder.

Let me know if it works for you.
