### ISSUE TITLE
When the collision happens and the desk bounce back, the physical button and app stop working

### ISSUE THREAD

**Issue by zeroarst** [tschroedter/idasen-desk#6]
The desk has the safety system that bounces the desk position back a bit when the collision happens. So when it happens both physical adjustment button and the app dose not work anymore.

**Comment by tschroedter** [comment]
Hi, I've tried to reproduce the problem but everything is working even after an 'emergency stop' done by the desk controller. Can you try to update to the latest version 0.0.97?

**Comment by zeroarst** [comment]
I just tried the new version. It works. I thought I already installed the latest version apparent I didn't. Thanks.

**Comment by zeroarst** [comment]
Wondering if there is a way to display current height?
