### ISSUE TITLE
Is it possible add current height number somewhere?

### ISSUE THREAD

**Issue by zeroarst** [tschroedter/idasen-desk#7]
Wondering if there is a way to display current height? Something like Volume2 display a number on the icon would be cool?
![image](https://user-images.githubusercontent.com/1834837/154788091-780b9f24-fb45-4dc5-b835-be240ae469c3.png)

**Comment by tschroedter** [comment]
Hi, I update the app to show the current height in the icon. For now it will only show the height after you moved the desk. I'll add a feature later were it will get the desk height at startup and show it straight away. Can you try the latest version V0.0.100?

PS: Make sure to uninstall the old version first.

**Comment by tschroedter** [comment]
No worries.
