### ISSUE TITLE
Change settings of table height and possible hotkeys

### ISSUE THREAD

**Issue by ducklingasa** [tschroedter/idasen-desk#8]
Hi Tom,

Thank you for this great app!
Would it be possible to extend the height in the settings from 60cm to 127cm (the full range of the table)?

Also if you could add global hotkeys (e.g. CTRL+ALT+1 and 2) to move into seating and standing positions would be great :)

Cheers,
Adam

**Comment by ducklingasa** [comment]
Hi Thomas,

1. It worked perfectly, thanks for your time.
2. I've found some example codes here: [Keyboard Hook in C#](https://docs.microsoft.com/en-us/archive/blogs/toub/low-level-keyboard-hook-in-c)

Regards,
Adam

**Comment by tschroedter** [comment]
Hi Adam,

Thanks for the link to the Keyboard Hooks I will try it in the next few days. I also found a few NuGet packages doing simalar things. I think I have to find the solution which doesn't trigger th virus scanner.

Regards,
Thomas

**Comment by tschroedter** [comment]
Hi Adam,

I published a new version 0.0.111 which includes support for hot keys. Can you have a quick look?

Reagrds,
Thomas

**Comment by ducklingasa** [comment]
Hi Thomas,

I have tested it just now and it works perfectly. Great job, thanks!

Regards,
Adam

**Comment by tschroedter** [comment]
No worries. Thanks for testing it.
